---
  - name: "Ansible Automation Platform Testing"
    hosts: localhost
    tasks:
# Below task will execute the list of directories and files present
    - name: "just execute a pwd command"
      shell: "pwd"
      register: "output"
# The Output of the above task will be displayed on the Screen
    - debug: var=output.stdout_lines