---
  - name: "Ansible Automation Platform Testing"
    host: ansible_host
    tasks:
    - name: "just execute a pwd command"
      shell: "pwd"
      register: "output"
# The Output of the above task will be displayed on the Screen
    - debug: var=output.stdout_lines
