---
  - name: "Ansible Automation Platform Testing"
    hostvars: inventory.yaml
    tasks:
    - name: "just execute a pwd command"
      shell: "curl ifconfig.me"
      register: "output"
# The Output of the above task will be displayed on the Screen
    - debug: var=output.stdout_lines
